<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>ipv66_重写_</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageId>IPv6Tool</PackageId>
    <Version>1.1.3.0</Version>
    <FileVersion>1.1.3.0</FileVersion>
    <AssemblyVersion>1.1.3.0</AssemblyVersion>
  </PropertyGroup>

</Project>
